version: 2.1

jobs:
  test-rust:
    docker:
      - image: cimg/rust:1.92.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Debug - Rust environment
          command: |
            uname -m
            rustc -Vv
            cargo -V
      - run:
          name: Run Rust tests
          command: cargo test
          working_directory: rust

workflows:
  test:
    jobs:
      - test-rust
